global using Application.Errors;
global using FluentResults;
global using FluentValidation;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Shared.Dtos;
global using Shared.ViewModels;
global using Infrastructure;
global using Infrastructure.Repositories;
